# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: atuin-db
stringData:
  username: ENC[AES256_GCM,data:MYo5/WvPufLRiCyOxL8=,iv:e/6/GrpdJRsLa7xMssPpXWYpfZlLe561RpfdKsRDy+M=,tag:EQZkhP8eNjZxdmsA0fTmgw==,type:str]
  password: ENC[AES256_GCM,data:eevPXrBDXyFbUr2/GCsGmweF6i8xXP/RSndKPw==,iv:pek53wr8EHYiQVaZiI3leZcqj0KY2v6DS99fAFl6ToA=,tag:0wD9B5sMB2/FvMxbfApk5Q==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdnRqOVQ0NUYwOXYrV0V2
        eUJhQTB5NldQZVo4UWcvWVNISGIzL2hmcXdNCmdvUHYrTm1FYlZWc01OWEVpclNr
        TDBlQWNja0krMXJ6dmpRTTRDTFdNRkEKLS0tIGxaVFNhYUpDemJsM2JoOHZGYUQ1
        alZ4cW1CUDA2UjlDTy92UEpQdWROa2MK7CIQE8wd2nRIMWkIPbIykJvr8wOlv6Fq
        1sJ1L5LzEYfCtR/f1SykO8XOs4eSo8jHBsltquyBIWGhqW1IgLigWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T21:43:49Z"
  mac: ENC[AES256_GCM,data:6W8VyXVet9ZUcnewqaGSsjnIILffPrdY3h+G/xld2CEyBZDh5OEs06jdDlgJsrUgtA9meo8mHZ7W0bWcWIcum3yda37E5Iq/somFaSkxAPD8qfkzqFpaKig4PNXQY37M9fcgUu3AywSRSw2r6YtI4fmBPXH6jOal+YORbpW5z4c=,iv:UVOFgxJ5RHZn4RoC5QxDZg+i/zJX4EAmK4I49r8Em8I=,tag:QGPLhFRQvyL8nl5/P9GpLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
