apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chart:
    spec:
      chart: renovate-operator
      version: 1.10.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mogenius
  interval: 1h
  values: {}