---
apiVersion: v1
kind: Service
metadata:
  name: octopi
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: octopi
  labels:
    kubernetes.io/service-name: octopi
addressType: FQDN
ports:
- name: http
  protocol: TCP
  port: 80
endpoints:
- addresses:
  - "octopi.server.internal"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: octopi
  annotations:
    external-dns.alpha.kubernetes.io/hostname: &host octopi.${SECRET_DOMAIN}
    gethomepage.dev/href: "https://octopi.${SECRET_DOMAIN}"
    gethomepage.dev/group: Home
    gethomepage.dev/name: OctoPi
    gethomepage.dev/icon: octoprint.svg
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/pod-selector: ""
spec:
  hostnames:
    - *host
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-internal
    namespace: network
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: octopi
      namespace: network
      port: 80
