---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  # not yet set up
  ALERTMANAGER_PUSHOVER_TOKEN: '{{ .ALERTMANAGER_PUSHOVER_TOKEN }}'
  PUSHOVER_USER_KEY: '{{ .PUSHOVER_USER_KEY }}'
  HEALTHCHECKS_IO_HEARTBEAT_URL: '{{ .HEALTHCHECKS_IO_HEARTBEAT_URL }}'
