# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-db
stringData:
  username: ENC[AES256_GCM,data:AwTIHUuFcxh+9WsgYPkN,iv:6fBxiUK91tQtL1WPuflUowUwY+4K78mA/n1auoPowLc=,tag:ubHMwAqGnJMLpilUuP+wwQ==,type:str]
  password: ENC[AES256_GCM,data:FBbXZA6xxK/hTRoud2hE4ZUN+Kugxdn5058mWw==,iv:1ZNdMiR3egiG5moanhdmm5B7/oCOxHpwdZ+G8zTfRVk=,tag:63gCx44Wtf8BI9Lszpat8w==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1g0cjdTQkl0T2c5U2F3
        Yk9IUzJxWVAxN01wSTR1dUpsbUxjdC8yWlc0CjYrdkpKd1BTRmdES0Uya3E0WFI1
        SSszODN1M0VzNFBIa2FkVktqYThvOXMKLS0tIHpvT2FHMFE4Y2ZXNWp0aHk2TnUw
        K0ljUGJ2TG0rT3k1bW1qeTZFaGxUVEEKpt1GVEARkiREP1cUKxUoABHrnrOpPpFS
        CojMxQ8J//vt2Wzkq2DKUWLKLuHOh3zNLH4CNlPY4iZTonXSynRERg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T04:39:01Z"
  mac: ENC[AES256_GCM,data:DRyLNUT4WsoCoZfKZGFikuyif6B8sLt/JGIJMz/eotx66yA+mOuUqZz5vQfGy9qRzyrtccWlKxlnTHie57CSjdDAAMotZ5smy/5Tt8DDCa6xtacI4ziGxjq+b2ZOrGAfrptj30t8mkLcvTxbbcyvncmkVqc+/VKzq4DJ95yr4m0=,iv:esvCJBLUJJc7+lc+vLtZYH8wwzXVj5a86eO7+kWJRtY=,tag:AhosloUXGTQSDvm4yzUZeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
