---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/repos/cluster-template
resources:
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./bazarr/ks.yaml