---
- search:
    provider: custom
    url: https://kagi.com/search?q=
    focus: false
    target: _blank
    suggestionUrl: https://kagi.com/api/autosuggest?q=
    showSearchSuggestions: true
- longhorn:
    expanded: true
    total: true
    labels: true
    nodes: false
- kubernetes:
    cluster:
      cpu: true
      #label: cluster
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
- openmeteo:
    label: Home
    latitude: '{{HOMEPAGE_VAR_LONGITUDE}}'
    longitude: '{{HOMEPAGE_VAR_LATITUDE}}'
    timezone: '${TIMEZONE}'
    units: metric
    cache: 5
- datetime:
    text_size: x1
    format:
      dateStyle: long
      timeStyle: short
      hour12: true