---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: ${VOLSYNC_SCHEDULE:='0 * * * *'}
  kopia:
    accessModes:
      - ${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=5Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=longhorn-ultra-fast}"
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=4012}
      runAsGroup: ${VOLSYNC_PGID:=4014}
      fsGroup: ${VOLSYNC_PGID:=4014}
    parallelism: 2
    repository: "kopia-secret"
    retain:
      hourly: ${VOLSYNC_HOURLY:=24}
      daily: ${VOLSYNC_DAILY:=7}
    storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-fast}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=longhorn}"