# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:6m6OTPpjlAvjqA==,iv:sjgwqrWxcVpfbDD88cCuP9n1ZEW2Z9uY0sgMYybqzCA=,tag:184j5hJVihHuA+sjfol2tA==,type:comment]
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:fCUOta5/slWhjhZW,iv:sYuG2Q3SUZdJelp2Htl3AX3hHLd5deV9VWlxpNh0bQE=,tag:hObwPPszm/OHu4sTBUwFUA==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:2VPwKoP2Gfo+pA==,iv:DEYKaH7wFdk0PXl1jIsJAG1CmX47puqDN7fY+Z32uzI=,tag:ldfXvxtRiFPQA+LCjR0k0A==,type:str]
  #ENC[AES256_GCM,data:WgZJT59G,iv:PtVPuNgqDOoIW/i+c5qHGCGDh7//O5rOyMhM8zZbdGk=,tag:099WIAthk+SvAisqjX4sSw==,type:comment]
  #ENC[AES256_GCM,data:KezYM2d6k/RW+Doj0bDNm0glH3zVeCjiecrSVZcOvdqmH22X6EKJ5nhnbrAw+lsJGICAHyQ=,iv:EGuG7WFFxsPDyjcB5wmjZoMYznEgaTgYiyf8R9WMhZ4=,tag:YRBAeLTol/tD7rCQAIwf4g==,type:comment]
  #ENC[AES256_GCM,data:j7IqKcS+qQ==,iv:SBXz8sDP4EoS7XMcHZuxTetvFBJEMaI63tvqjt+ggoc=,tag:ZVMAbra0M+9rlY1+jT+laA==,type:comment]
  #ENC[AES256_GCM,data:FybxTDvnvcarA7z2j+iHAi3XmJyubU6pacx527pPvsCuAJSkwLx7gbmuMUl8/tpslJuRp9Iw6LysKJASc+s=,iv:J43n9K+piKgV/k6hFrTbTNOXohjsigGpn5kT3tZpD5A=,tag:E2gJ1e3Q+fqqXe7dgHlRpw==,type:comment]
  HOMEPAGE_VAR_BAZARR_TOKEN: ENC[AES256_GCM,data:GJ3Q02RFlM782WLc4B16KMYsuqC9msuaNDkBqusnKiM=,iv:RwqLXiLJvzN19MLoqoRSdTpm03KRtU+Z+FdtWQL2NnE=,tag:7nCCnH++JE1I5+SwgKOB2Q==,type:str]
  #ENC[AES256_GCM,data:j+9Re0HJA6C8XUi0Kzbm0lGiCShg2nbO68OpF3qpoakpYSEP70lAb5eN2wHy5DmV,iv:spACA0sec4zQ5ix1/jY4OWSLruIsa3VBKPgB0e8Fdm4=,tag:XmGgvAtIcjYGZpfQ9GS+KA==,type:comment]
  #ENC[AES256_GCM,data:xklsV8EswYGx/KmARt9zag4KIax0tVpk39flYRbVJ40cHZsJi0CXmMN4pBpzKhMs,iv:GCqIhs1js6U9HmnyGdSvh94Ugcz21IWFVplX5LURMDw=,tag:i+BXmA2J04he9Ed1xFAjgg==,type:comment]
  #ENC[AES256_GCM,data:HvnArMF8AMeCUHuOXORTDXYrohZUXIwIgnCXpTGGecVAFahWiVG+daLZfv4ZeMiW6hajJGSr7koxeA==,iv:dfGAx1ZRZQ/RQ2fZA2LS8qPrh62gjiaEFbx3v6pmRvs=,tag:K9Cl24a20uMnymUGAN7w3w==,type:comment]
  #ENC[AES256_GCM,data:kuI4a6rAF8Cd9mXDhiLF+qgvxiyIW5ZVIzNsN2R8OFAx29Dnd7/jCb9nCfpdsri7lMM=,iv:kKaR2SN9QdNeDd+wa/Bn2Zaf0Ozi7ar9RKjwpOm0z80=,tag:BKWvmE0puQ4VQFocSnWS+A==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:bajeFti5cVNDTOb3XCq/J1nkuDA=,iv:JwzT+wXLeyEafcaW+/dc60dJAJLaASaPZz8oPTO2mpw=,tag:caaUDKVh39tXVtU2w+O5Bg==,type:str]
  HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:rCoXS6/5lFKIjJWKpRXC1kZbaBFQfP6w9knWH62Bs0k=,iv:TlIXL8T/tLoGw7Sa7Z8nEDmt3oi2/cFHM7x8d+ExxEw=,tag:GK/JhXhPEXTTqNdlYkL3oA==,type:str]
  HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:PwJSQskOeEe+P+jwPdAZ96eRQH2CZGCR62gAKEXhJlM=,iv:IYxq+0nD6LaXax0i7h5EdXKW7MwRX6WtXCazrbUUL50=,tag:MW9iOsMWtGBpxBoLVKQxxw==,type:str]
  #ENC[AES256_GCM,data:jO/THU9hCRSb8GbcUKrEGEKNC2g/5rgdUmQk4pJY9/4V0QPLq4m26BVrr559sDynntt6YA==,iv:kGfG+AaJKBc6+YCRQhnpjIwmkeXWH51uc67p6whIjqU=,tag:oQ0RIvlSVt45kMbLq7UTVQ==,type:comment]
  HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:INpOxXhNO/3F9JFAyKHZEzOE6aBqCax7ySN+JnzKIAE=,iv:J07VLhX9tzOq3j3gfGBdsFgc2y5+MbBuMjxJLQFAbj4=,tag:xEK9XuBcNQKmEXra8ULc7Q==,type:str]
  #ENC[AES256_GCM,data:eiHmp7vBjKvPIij35m8GUVO+TSddjK6PzESNudxoRTMi/Jp1xAKDmgZIupz70j+Sjj5ZMee/,iv:/6gWFeOeKil1itGLdE0QYQr/43h6Z6FTVT4Fmj7LmzQ=,tag:ZI7yYjViDRoO+aPh+fZEdg==,type:comment]
  #ENC[AES256_GCM,data:1sObZWptMJrKN9V1tQ==,iv:JSQopp1cJA9OjSGsTQuYsTV55ydJgbzZJrWK5+Nwe3s=,tag:ssI+MRdEyaut/c7QCT1k7A==,type:comment]
  HOMEPAGE_VAR_IMMICH_TOKEN: ENC[AES256_GCM,data:YscuX4x4vkVznb56L6RJIOY5/WprQpDf0y4slYiAcHilzJa5lsKzYXAe,iv:N1U22B/4assAr//Yql68wRemCBfBVrZrN4K27SSNs7Y=,tag:BrDr6tyP8UBk2HKMjKAtVQ==,type:str]
  #ENC[AES256_GCM,data:6XwwpsXl27PpXQccNY8PtmCwKtgSbatAhT4DC2yjYEZdAkRLBF8YBYwV6nAyrbMDmmckUNHFkXQ=,iv:gFiOJljePrf2XvAgWSh1ETXj6FW+9Ws+s1rZgvzlY5Q=,tag:13j41fwmvbEX2o2+qyGthg==,type:comment]
  #ENC[AES256_GCM,data:kVbIqHqbOQDKKA==,iv:lUuPfBSier7OZC4QT9JJng20E+5jdNf1LWPqYV1PFs8=,tag:8w2s3cXB4BndcJIe23SexA==,type:comment]
  HOMEPAGE_USER: ENC[AES256_GCM,data:K3RrWKxUXSY=,iv:ofV429/q6lSy4ItmC/D9Vx6OChZOIe7xyO5Z4c8OZMs=,tag:haP6DYpEMK43F5LDeGRypA==,type:str]
  HOMEPAGE_PASSWORD: ENC[AES256_GCM,data:3vncj7SwdSYPKYCeEKXGb3trdSqz5FfcinUU5TpE6F+7O9/u6pnNUkg+x9tl/hY4Pm01myGkcTz6Fowk,iv:RY/qx3XEr0buPsVA6iQyk1F6lFAr0vs2TPQVpFjr8lo=,tag:RY+bgCtF2EJQ5N2fCucweQ==,type:str]
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:UwgwZq2/aS5cDPymXUZ3+7l1AMRng4lghDzFG48a+56WdX84Y/HsZ5pRWv6PFjcuelJcyytChQeA8sVJ,iv:BLA3Epov6wYc8z3wjN+h8LJmtHB/fW5iPBUpd4SuM0g=,tag:Deu6R3kJRrQMCZzdaFa4Eg==,type:str]
  #ENC[AES256_GCM,data:MWqP7QxqiU16WUKvYnm1/Q==,iv:XVq/weNI51jUEyuSrj92wk/mhDDLbVz74/mlF8tlJro=,tag:hLi4XpgZR4zG36Bl7k/Z6w==,type:comment]
  HOMEPAGE_VAR_TRUENAS_TOKEN: ENC[AES256_GCM,data:Ml6u4watWYh3NdJ9H2EdDFOo0JL9kK8Bhz2Ew1ptgxboYQNnt57WNtI62GUxY4C51gNzz7WNjxyi7tlWAb5eKJIu,iv:h120FWm+4b0ZlQecoVYwM3YNMtV3Azivy+Q+p4Bp8uI=,tag:bSIjQArT3tVSun+o7aRaOw==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOVpSU0FubXFDdnVNc2NU
        Y3V5VUd3blZwRUJOeDhXZGNORzF0aWVaMlFvCkVMemN4SCsrdlNrZTIvVUdLUnIx
        T3UwWVB1T1M4Z3A0MG43R0RkamE0d2cKLS0tIFdhakNPbFBCUG1Ha3k2N3JCTS9y
        WHhsZ0pYbkRxOG9qcjUwcjcwbkNXVjAKIE8h9bz1+0ak5zgObICRftUdDY4m4Z5n
        xVn7Lgssx/hEanR9+yQAya5Lm/OBheSXgaR2LHDjVCKN8t8BqmRvPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-11T18:39:21Z"
  mac: ENC[AES256_GCM,data:GFlLbEB+0LMgB7tNmSu7TmPmV/SrGG4BxNzBoPtpvq4bcrOHLw5mYox+t7LJ0i4uCeCyz/kKqJkR9WBuvjZDYTLEamTVJK7Sz0yTKOcZ0jcBzwSvbxlH0o7ATlnw2eglOV+WUM/paIVkvIbd6f013nr5wEbpknx68Cm5SrzSfl4=,iv:cR9NMTqd0w3T23qDO0fvDAPQZHzLTpTzDjiZaeU9u10=,tag:xuJCvp7XANrwMc3ybIfo1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
