# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:F5ArSPHbBXZQVA==,iv:yTZ2QnKs27qbUk+BeFkQaO5TVjAa/YJrVZnWDAfOYG8=,tag:HiHFhWM85QLHxbatfeAhcg==,type:comment]
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:WxeLqFJxN5O819oa,iv:jDvL2E35Cv1WFS8WlgzpthJBYz0YSnp0OYBCY2/fu3A=,tag:ZbZsBDyhOtKUVGcLVT2/SQ==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:vG2nCXlU+giRDA==,iv:HY3WNmlk/gh9t9RfoxcLOI9gYAwAAK+a2fNo1UsR48o=,tag:OVDdWwH5YT92IKJPM39CUA==,type:str]
  #ENC[AES256_GCM,data:MeDt1GKm,iv:GdZ4/jL6qi3AGgvbsSs/TQnAH6jW2d8zdAkfP+q3z+M=,tag:jdFVb70wWKwXRKfNWBfY8Q==,type:comment]
  #ENC[AES256_GCM,data:uV/elzOBCblZSmdywCABm8RhGeL7L7bm68BUstMau0qMWNSIdAzkpILOSddHZjMiYzmY4yk=,iv:v2PPqy44KfqDzqnIRD4yv0SxcwvjyW76NFtv7np21Go=,tag:PPEIHm4dMEE1J+FrCigmLA==,type:comment]
  #ENC[AES256_GCM,data:MNsCmDfJmA==,iv:yg8Uv8Pub6091On9zVg3xjCubiube0Hnj6Sj42I2Dn0=,tag:Poty3KqB7S9wWzKmA13dNg==,type:comment]
  #ENC[AES256_GCM,data:Ih4Mb423F8Df2dd2beDaIK1/XXFEBysiTk+NWARHE6/eimMxayx8YXqiiKwvaUDMR+eGNyApBdJx5LpH63w=,iv:Y5ZdwwzVTidZZg5ocKP36aS8YoxLxaBsUh5CBjX6LpM=,tag:ZNmy3CkTrtZ3gjzKluHwow==,type:comment]
  HOMEPAGE_VAR_BAZARR_TOKEN: ENC[AES256_GCM,data:zE4GIbMo/AetVgqX8MBXuSkTrzUodxr6K+g6M+nZrNE=,iv:gKEy0OLL8gC6Syj93y5zmCrjVJ9+a5l2mlvdDVOc/JU=,tag:RylqjQULkcMwGoAZSgsp5A==,type:str]
  #ENC[AES256_GCM,data:l0814wYMUMDUbp8O8lI3iVtcQ3B8GE+ZFJyB9xuVyrMmLTJXdQ8Lo4JOgcQYarmE,iv:W2KSsqn+zzaVt1IHhx4CNDeSqwtcJthsy2Ob5HFgxrw=,tag:GVV1//c/JxhUn484VS8sxA==,type:comment]
  #ENC[AES256_GCM,data:T14lIhQ8p98uCMBDoJoKN+vCDpuv+lAiPuCKknjm/uPH4yiakJQHEYyy2oWDvVRg,iv:LG7KUJhQiNCf4o+cWu4U8MLycDCC+biDN/stl5UZqlE=,tag:7bP7z/Ok3O3XyOn4aYb4FA==,type:comment]
  #ENC[AES256_GCM,data:IZd/6LdKBDr++ISZ7WYHBcY8Wtm92pj/h7faB+cfpET4CbVsxb7uOJ8GFlDQEdECVqCL30kOigzLSw==,iv:ThoALi9x/cMc07sL/vybHWn4sxzB3yuaImHCpYv6Jy8=,tag:pvk4DhnuulpnAZ1nI6utsA==,type:comment]
  #ENC[AES256_GCM,data:q7pd6e0lw08+y6z0jdszebCYxl30OheynQ+wEo3DMD2CxrceJycALaqTj/lZeB3RfgQ=,iv:qdzIYSWwnC+/U3HiJZxhQetGnHKpQAySLUqKPhXBvRk=,tag:xSgDGAw1ns+EtId3Nvc37Q==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:w5sWjp+wZYCEueQOIDOQS8qHPZs=,iv:6p7JPX0roFwVJl07mJtyEQ6gU5kARoVFFT30mI/DyyE=,tag:d1i9FMv/gF383NRCmhvong==,type:str]
  HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:ZwFMzLwRHDh6GLotvAEYRVGDUfOpBP0Bn7LaqxefY6M=,iv:/Plo9rsyC2cfs0Fv66a74H7TpHYyXLnm8UanHPrNvXo=,tag:TbQvgsv/dAItbVRWvQB1NA==,type:str]
  HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:+KUDIGB0rEgTs4frIaKWeTunXx6OGx3go4caQqDsDsM=,iv:6he5v04dN5qfS5N7L184ok+5u2i1QJsm6Aq9oJ1XvwQ=,tag:k+spY8D5kp6cA5+jycVTmQ==,type:str]
  #ENC[AES256_GCM,data:0msJ/MpFWgCbwbMsisHL0hGCf8LzWsGaVjMT210ogwrbRtQMZpduEISYRMFp5v0w/jIKrQ==,iv:/7IGqpQa03ktqdVgbnMUrVJFEbj7DLouZCwhhfnaJe4=,tag:du7S7z5tgj+ccb1nEq+3Gw==,type:comment]
  HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:gh9ZUq1FAccF9/m29zSxYpNZb1IAYH9j/5zovbKeDSc=,iv:cGLQAXbKWTy1tsbEfGcH/DeMHBKH0nhjAiL1NrzK9BA=,tag:1Uz9v8cihAUndYdpk9SYMw==,type:str]
  #ENC[AES256_GCM,data:bqrfORbZmKhSpSIYhgyJ64FXyxRNujfRVcJjOWzPjzAMZr7BiVazbgE/vNEh8PzzQl8bNXgE,iv:ESLq42AK/rtqZ9hI2YpzvGgnWW9ChOFSABKf5HAM97g=,tag:1cxM1G+lrdXho8XYm1BYJg==,type:comment]
  #ENC[AES256_GCM,data:nWHgiMItTwV4NgPSsw==,iv:cnLUPifc4IJz1HeCpqK4Y3rKufuX407cAbbQwy8ldLU=,tag:37Mr3NjEWiPTPLf8ZDjpgQ==,type:comment]
  #ENC[AES256_GCM,data:CY+GLlATBBKWZ5hsvoqfY8gjC+PtkuHG+ycrjLeFPlueulQhBaRvoff/d4dAuYjbReU=,iv:OFubexxRPMN2KukAa4LfR66pwISTeRJ1STQw/Zbh5bc=,tag:oVDkDy6sSni/wR2+g1rr4A==,type:comment]
  #ENC[AES256_GCM,data:hYV49Qq7jAQkv5XyiewvhlAWVl6WqxJsJq/I/lpMR/VqV5RPycwUzrfqhbgph2OtEhtZQw7YVfc=,iv:KjXeH2uTipCIQXtz/t5YNcMconJ8oY4PbaQGWaQVl1w=,tag:94G7Jjv5qn0ignltqwORkw==,type:comment]
  #ENC[AES256_GCM,data:o43ubDQopDbZxA==,iv:adADdOa+b0bDf15ipiNu4m8iysybI2DEQVipRypOSZw=,tag:0PgKB805QQdtmE1GcdNUWA==,type:comment]
  HOMEPAGE_USER: ENC[AES256_GCM,data:nIvQi/4dbM4=,iv:V6OPD+pQDVpXlWVq0vkIDNH8SY9VSdny8rrTxrLLl+Q=,tag:EkcOozVMjgcgiARjP66P8w==,type:str]
  HOMEPAGE_PASSWORD: ENC[AES256_GCM,data:BB3ceRH9tJHtGCAVCxeIhHG6IeGtgvnhtNH9E/crPzO6LSilMf066w+5gqajzKSN/h6wWo21OLK+YTa8,iv:kA/PoR23AB/6z57r9NxafbG37jTMKu3hYKY8ddsyH5A=,tag:NkcWyPxC361kxQI9dY0yrw==,type:str]
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:DHr45vFrMrXroxBQ8FzvAJMwxfleEEKxAfdvxtzfpm4rH1mk7vMJXQXWdJe5vyba/Avd68ZsdNKjEzYC,iv:a08GurLWLzVq+26ip2lB7rvhiFe6MR3JZulpurp1JkY=,tag:3p4XUaiP/pNZros6TEur3g==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUUd4Z0VPdTdrODFVOGFw
        UTFrby9Zc1BGSlo1S3BSM0JiOGt2OEJ4LzBRCk1kbnVzc212VWxEeFU1U1NQcGpu
        L1NnZTAzVG1vR3BxTzdsM1A5YXpDeXMKLS0tIDdrcVJ5UEQ0Nk9QbysrTTAzVUFK
        S3hHcHpmaVJIR3JWZUhHRy9uK2d4eWsKXm7giv26sSdKQSBt5Efq+dpAhcwThxay
        pG0BHKVgfYhZTWP6x5rhLnPhdkwwO3sm6DOBCBv37Yi5th0BjehCXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T07:15:26Z"
  mac: ENC[AES256_GCM,data:w2K/4Tyrku9bDUR1hieE1cbB4RDyvorWbO+BZvTD9ALmHf0qdEYfbgmGOB88KQbP3JZ1msv4bh65zrV7K9Wg0CfEFSmbzYkfxuVfoKs0IXxHKy+s4bFHxB6iADMtpx8SflIyw1td+x1+zKJhpJkmt3+hDkbJQuVOPaX1QUxKlI0=,iv:shcPBKDS1dhvI1/GrSGClS94dDfxtqfgi8xkz0SxAq0=,tag:XaQ0S8MtY4/DAfusevKZ/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
