# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:y44FvHJ7y+zFPw==,iv:ybGmMKcajz9w8vEp2j1X/7cXrLtch1Hpwd1zKVF20jM=,tag:ZCgRrMc3Ze2FrKgPz0sptA==,type:comment]
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:6brmF/7Y8qQc7Cnj,iv:DcrMZ4ZvZlrV8U/yqXttRxqogBsV9YtUVJEolFfDpnM=,tag:vLil5d+7FhLG97TdLy4FcA==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:TnQ7fgI+P7b84g==,iv:vCkDoxy83Wpj8KIIUAtMhGkpBHNhIWOPGs5IT4Xqymg=,tag:8IxZtcrNmSVT37BhLcUhrA==,type:str]
  #ENC[AES256_GCM,data:+XFpJQCd,iv:cn5aGZcJqfPRVvkKhTwaQDv2XMw1LGO2mkRuv/lDTNg=,tag:imE67iL6a3SXfM66ELQupQ==,type:comment]
  #ENC[AES256_GCM,data:nBWGmjSkEGZiTJ6aAlGkEQ0RHk8daqeFpBXJp0Fr6SYB6Nd6wKSc2hjlwF6WTRMHZzADTp0=,iv:LBxNHH0+pIU8pqAVfqEwcbmcI8wSZMprgyMHJBRQdiY=,tag:elI5ABwLOq2GcPtYjie0YA==,type:comment]
  #ENC[AES256_GCM,data:d6WGavRVaQ==,iv:xoI7b7lRCGPAh6DENT7pDctQq3KLTLRCEN+hqHumBJA=,tag:k2AYE2Z5rNbN8FTfrc6yFA==,type:comment]
  #ENC[AES256_GCM,data:Mtvl7ZoNKNjUx5GSCLu139Y2VQLe6W52fSOyq74fxOVZvVLXiEFjnpjExsN2WwZm8nNF+dgyyTkvdn2L5/c=,iv:ri0fpEFEEmr63B9jZwxTLa2fLDDQvNrjvE3gWx5wSVk=,tag:FfsSw1/4j6sfTq+YGjNQ1w==,type:comment]
  HOMEPAGE_VAR_BAZARR_TOKEN: ENC[AES256_GCM,data:YxPqGRMAkzkPRRRg3Ts01jZIAT6R+vs57PEN6HkRxtM=,iv:88fMWEiG4kGOeYwc50d8LS4jhLePvrsz6mDimIh1obI=,tag:6/cr0ABKQ6aXGvWNYrCpQg==,type:str]
  #ENC[AES256_GCM,data:WWbJM2a+lvP659CUAMYTTs9PLwXZvSfsjfYAnYYZWCrdDWFdDdwQpC+U4O6uOeWV,iv:qD8QrWhUUnN1lkDJx3ldNuNmfGfFGMCifDydQy71ddc=,tag:Hz33QIjFMDogeg6nIFIsCQ==,type:comment]
  #ENC[AES256_GCM,data:TtV64hcfkWjGrAx2RrEUg+NMnk4wtWvoA3GH3mzidk5hMnnuvUiaJuaFf2bJAlvc,iv:89WyxsCfuBPqTusSe5XCNG9Imy3ec0SXRNdrWVMA5QM=,tag:3ZUzFrSHHnF6Dyehv/RIJg==,type:comment]
  #ENC[AES256_GCM,data:YQtSFFLrGLr7mlYxCGpK3n+rj45MGzvofX+2DEYLRGFtFi6LIZ3PChba07igEDHpmh0L0JHjVLQ46g==,iv:V5XFj/nJdJT+rvrH+KvtbLsU51d+ttFjdox+cYtN9nw=,tag:NXLRQvYbJ5pB1m0NSPvH+w==,type:comment]
  #ENC[AES256_GCM,data:y71/fo9oxH4fLrDqa2HKeL3bz51aaq+aEtX8dT5QAehpMLSx3TSGSefKzaXNIKGcSWU=,iv:+dxNXUEwLXQ8ahx+K/+D3KS00CbSq8BuS51PawCxFDg=,tag:q6SCHIzeYQmLOX1xUMvnTg==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:a+BdXR0oHSsDTXJ7XxhgSZFYaUI=,iv:IMX6TulGC9Y2ojx9LjlI2Y157G0K4UkIIfMJOwxAkQk=,tag:ZvvHlm6cbsN+vpbTb9URoQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:BYbZRF3qLEWoKUtcA9X5KQ9GgFKYIZKEf/iU7RrF3H8=,iv:x6HWCdZIXaVHhO93fh7IItNS9G13Z5lu7vpJag//hwA=,tag:y/v3PCq5uKDVIItPtdHrSw==,type:str]
  HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:KMytSV/KdV+H3PAyWpiPK14T58Zf3P7a4n7j04uvpic=,iv:dVspLLM2Sy2ixQjwB/pHPe4O0jYpk5p5nYK7vxeD43s=,tag:FCRQj+5N2uethpxZw8FmVg==,type:str]
  #ENC[AES256_GCM,data:dR026BCEMzfd7nmSPMBdvX+BWLwT+g2ZfYrHHyBBLbS39BdQiHvPeDW8gSZjb6wJkfKalg==,iv:u9Ax5sxFe3uktzRqhxwm4j2Q3b+xpVodzFKSad2jWtc=,tag:ggfzLGezTAUdv7Z1aNwPYg==,type:comment]
  HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:wa3X/ST2/pNSnXy31ii1jPX6G9npPnvZAd4PfYso4FE=,iv:dK0rVpBO/McIWs9NoFKaWnfWFqIxokWg+mvIUzu/Gns=,tag:AZa/NoovyPDQCWNmVateUQ==,type:str]
  #ENC[AES256_GCM,data:SQNNAIyeR00kVsYnnphftduJ3Y/8QrKVBtyRURDIBClQjJQTEU3gS2WQtrgut1GQtGeRCkBX,iv:cunM0gQeX3wl0NYAz1XWUIx/aFJaN34dZSELCnIUsOo=,tag:c+nqTA2hCZeiuZ+nW3aEmw==,type:comment]
  #ENC[AES256_GCM,data:sEASxeuYymNMggPiqA==,iv:VmU8droLw9nxkmDcBu0/nLDuk4crJyZZTJYQ/ivth6w=,tag:6LrUC0TaoPJxOIpgzuOMig==,type:comment]
  HOMEPAGE_VAR_IMMICH_TOKEN: ENC[AES256_GCM,data:iGKqyrAYdgI4VltG2lGVALuHUBPne+GYYayCbD3zC4vv7RDhvcvAX7PV,iv:Jwv9DzwcUTxMIs4rqSWxcNsz68yX8uGtGHXowdybqiE=,tag:zntEfTbjrpcRbO/2HACm3g==,type:str]
  #ENC[AES256_GCM,data:6KIBMHuIvHMXnpU/DZEL1Ka8WlYGuPMSgZPr3mcXbjat4agTJ1nltv1GpzlTetTIxOkxodwfELA=,iv:FZm9T84UZnRY/86nepNpwmoVWax0nNiwtJ+isTcIXeI=,tag:blsBLY8Yf545E2DbLDk9tA==,type:comment]
  #ENC[AES256_GCM,data:9LxrhIL4zCTfSA==,iv:CzKNoBAGbA2JPmnO3ezsgeJ4vqqfTF/J5okM2+g19/c=,tag:3GrNza292YwZED5XBDVfXw==,type:comment]
  HOMEPAGE_USER: ENC[AES256_GCM,data:zF6pEzUXyf4=,iv:lev5jU2MJD5rgevH/hyFlEw5U16FIbKqGfQFtSRTnSY=,tag:lcnTQjsckKlonV2+w9WAFA==,type:str]
  HOMEPAGE_PASSWORD: ENC[AES256_GCM,data:lguqrwBqeamqbV0aagFZxxB3rJgjSbCMYPpbtu9/zGgVpsFN2ZBjEtuOWuV5bBoZJFvWx3u2dS0vPQYf,iv:pwMJgEt5AV8EQlPWPLWoYTM7drNVNv31UhUR9XgOnug=,tag:jt0BZdUSAwq0lKD/xnpndQ==,type:str]
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:avBONPUKRTuW+FUdqROqYbMahJfSoNMoIQYgu5rXmN4FV9XrNlIbzmP6NtLuGbhTZDwZi2+RzcZPQD39,iv:Wh/uTirOh5d6Zwl+5z02bECPIhvgdpacmFGEIRyGugs=,tag:CRimUw30H/1Fnr0DDx48jg==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT3Ura0FtNFQ5MTNuUFFQ
        dVdSbllVRHFIZzFkNURKU05xNVBBZDBwbUVFCnV3SklRcG1lTW9xU2w3TWh4WHF6
        YTIwUEJ2Y1l5aU16NStvNXR5S2g1ZFUKLS0tIC9SU2JMVTdQSzhEWDBVUUJtbWdW
        eWdiMmdyUDFrQkRMWW1yQkZybm85ZFUKK9lQRBawCaeAfgKOJZvVk/5zB8FIG6q5
        ambwWYYPoBXQfjCesUGBZPVJk397/qCHuaFHPUlP2cFv0uszJCudWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T23:25:23Z"
  mac: ENC[AES256_GCM,data:Dmap4pUjbE1WZXki3stsVgFmOdiUBygiuUvJ6Jo5xH9OVliEyj4e6KZJ75+RYVc5ZWxlpzJ/oYA+Z0tRXwEcr0x55LHSOt0tMT46BEHermcTb+dzRyhy2AOu4PfwNfWwkBwbzE2uB/j99dKp3oyEajklZkY31AlkzZAYQFsg0TM=,iv:5jHOjE/pXIXvwNIN2Aph5c2IFHmwNCIP2AzLG/eROts=,tag:ZH1RxxKWXIYzZT4ngYyVjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
