# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  #ENC[AES256_GCM,data:70eOrsWk8v7Tkw==,iv:P6sefLopLwJyxe/zi9BnkXqwMQa+7RCfzPfeLbUMu8w=,tag:+5d78WhDvmNMEz3muYmcZA==,type:comment]
  HOMEPAGE_VAR_LATITUDE: ENC[AES256_GCM,data:o/JcOCle0ZdNsXeQ,iv:fyN3ATGjTcqfa32Orhxtv6rlUnGvlEicE0Lks260F/w=,tag:GZLyXYq2RN2D+NFsylGpBw==,type:str]
  HOMEPAGE_VAR_LONGITUDE: ENC[AES256_GCM,data:7P0kyUgu2ff4FQ==,iv:Go4oGws3pkZm9RlgRR7yN/VcUuC88HIQ8CJPWxosAT8=,tag:9tzHImbGcavuJKw/MhyEKA==,type:str]
  #ENC[AES256_GCM,data:tMpjyxA2,iv:SWPL5JOeeRZvuJdhXPKWXgtIaBgduPWGtE5HbPyZqhk=,tag:M5Ek4OFc5dyXEOLFVIDGIA==,type:comment]
  #ENC[AES256_GCM,data:f1EQWxs2RauqSprIqjQl8LYIW5ymMaqq/eDTo961TEbbRYwZR41rU7G+5HfKaJmLGet4fe4=,iv:ctyCjhl7kfBAwmAdzeZh5WI8ZeBP71io5RcGnjz+oWo=,tag:E87Tp7DF0majbU6JLnwtMA==,type:comment]
  #ENC[AES256_GCM,data:dmN/dN48+g==,iv:8LmUm+2Qidg2ZLw/JZxdSlsw9G1i3+wJxH892SwrQoc=,tag:kfKAO6yvzllX2D1RlvHwdg==,type:comment]
  #ENC[AES256_GCM,data:PLlEO06LXD/zmj369cIMrZ43U4/hJbk7ZYPYORuk/B7s2QpqcTJ8VvTsoYEoULFPEo4FwdkrbMwOrbrfldU=,iv:8T5AS3ljtaurX4j8v63/gJ8Bc1Cc7aNReLneR24jEsM=,tag:Mo8l3tLbTalhb3u6m168ZQ==,type:comment]
  #ENC[AES256_GCM,data:Sc72dqyNj5kacmTzgAQk7jr/zVtzYddhVI49xz6Md8LP1UGSeOkw0nIkxTCoph9cvTi+,iv:YvHR733/Y63GeFGjdzWPj5/di8nj0dmJMCNnEoUy7Ug=,tag:pSfEf7mbPMPkeTS2r7e5tA==,type:comment]
  #ENC[AES256_GCM,data:kbJy5JJDi35V6bv/OxjR6elYozR6g9u5EpWllEs4YoFn95wPYQ9UnrR3kR+TalaR,iv:Xj7aA+ee3m654YDf/ESROCD5nGIGQxtyAk/XBtZq3sY=,tag:7ZEaZ2cANOHip4MjT/Q75Q==,type:comment]
  #ENC[AES256_GCM,data:rscKvorEgSa6MCTOgbKpeOBOz/UoJyZjcDGdLKCy/Q++JRug45Q0BHlKs1FoENNG,iv:IyCj1GxbziD0G9HvghnZSyQLF3pEuYsc4kJZU0xY5sE=,tag:pdVNTf3gFVRsqCQgpVI0Bw==,type:comment]
  #ENC[AES256_GCM,data:4ZwttGfffBox6thF862eHmswEZ8iQElMkDFoPfe0vtzZr7X+D3t57YCChDNTABRkkTH1+JSKcKEiAw==,iv:mFWzkVef78IH72Jbntb46o8jrT5SY/gj7EaT3VrQCNc=,tag:ukD8n78yIBPJmLBxPQmI5Q==,type:comment]
  #ENC[AES256_GCM,data:R1uJdWJPN63COBrrgTMGs8Dd0G2zZbEpMkoYk4gX1c2E03eL0GCfsaCDlD2I6URpSeA=,iv:Q5Lji9x2lhFbu8RAv2jkJZoUm+mT1p08aJwFv4FCtPM=,tag:NLnLYUtJT0DO0oR5qvC5Zw==,type:comment]
  HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:53DoSGD94FzV0G9X20pJK0F9pDo=,iv:BxumxK/ZIhgf5CD7MW5an3PISpQr2x9aHOueXzF1b6k=,tag:7E7KPbiJUXTIm+9FBIZVUg==,type:str]
  HOMEPAGE_VAR_PROWLARR_TOKEN: ENC[AES256_GCM,data:xpdHQsNZpxNVMDwEi3SjSl+ZxOqqskEDmk7X4DsbpB4=,iv:KQ1b5UvmXYVRcqcat2+//eRkEbd95GgZIdUp3PC7wD8=,tag:9TGLhcI7OoKBfuxTUe3lNA==,type:str]
  HOMEPAGE_VAR_RADARR_TOKEN: ENC[AES256_GCM,data:WSmjLhmpWXupJFOIx0veLJF/AE0dAyrPjlTgwMfCgZs=,iv:wXFNoLCTz2eMRNBWahFYrPThVZn3zq+CiYr8eIbibso=,tag:Ba7cT8ISgaeTrd7A2HMlPw==,type:str]
  #ENC[AES256_GCM,data:F4DFDDSkt+zJ8qwHc/tUWVa3+eq9HLdXPRsinIghVEF65jPdv55AD/PlnF/Bnm/+2APGNQ==,iv:x+5uD2JOQF3oRRb74NHS+b1o3PDQ6dPiFdRVnoy9X2I=,tag:690RQXrXB1Ews+SWjXSHiw==,type:comment]
  HOMEPAGE_VAR_SONARR_TOKEN: ENC[AES256_GCM,data:DpePu+uOgsW2fqNZeyZ/tE1kW4IRjz6p4s99OzoSDdI=,iv:xWyFhoLxS9JXqjnpkUsZ9FjO9MeCdQJ0W8Y0QpWaZn8=,tag:YMbsrqL3wr8lUFaWViFGIw==,type:str]
  #ENC[AES256_GCM,data:ehp9eyFs+zCXmvy6NMRQyn/ULO+1KBtyA7P80uo/wc5iUh/+hBM0+rnjO0z0KPuuolHfkDBe,iv:GZLizWQ5oTbVP3fU4FrqvITPqCqnJEwRVV10Or0xj4o=,tag:+99HRDMdKgkRuOAvuad4Vg==,type:comment]
  #ENC[AES256_GCM,data:KdaiZyHBfZqA5w==,iv:wNWmPBh0+bP2RGzVifeaH3CGTZahNvpVjt+76i3jTi0=,tag:y7UQDspzGg2C05OA8SKsWw==,type:comment]
  HOMEPAGE_USER: ENC[AES256_GCM,data:HU6uEh73F/E=,iv:GQ3/H2N0vbAODX3XxJ9U/jDH92Dlqk/+UQxs8QrNVCw=,tag:y/jRVZXTkDUBElyL8ABiGQ==,type:str]
  HOMEPAGE_PASSWORD: ENC[AES256_GCM,data:VSbVda+KeWGpilCjHECMXXJiMgfVH7SzMr028efJaRDc+UhfceB+mwLqFjj2eyo0U7mMJNPFHyJDkLYm,iv:TyCAKHLY27yXm83jz2XaoPu3QO/wxJTh/nRs9MLRqPw=,tag:3Py+kj76tjdb37bqK1AgmA==,type:str]
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:ReK+HOmrUMq2+SlzWm+oO3akgXvVrTxLG7OA6mIFU8EwejqZO7kQCdJJe9aBemL+5/SlJ8Bzf3Z9nPQp,iv:VpEBXXiDFjamOcOZZrXEkEsDOxNzh0PiWEbgB0kmmVc=,tag:vpH0DLdQVc/iznrqF/xDMQ==,type:str]
  ## Self Hosted
  #HOMEPAGE_VAR_IMMICH_TOKEN: '{{ .IMMICH_API_KEY }}'
  #HOMEPAGE_VAR_PAPERLESS_TOKEN: '{{ .PAPERLESS_API_KEY }}'
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TUFQOHk2RHRtNXBYKzJZ
        MWc2cVc2dEFZWXVmYnJZZVJjL1cvQlRKRXhFCjZZTzNZdDRtLzcyakk0UTUzUUZH
        RjR4R29wd2s4TGJPWE9SYlVWY3VLT3cKLS0tIEwvWUpDVWFJOU5Pdi9JYmdJZ2Z4
        RGV4UjJmeitZbVpVSHRpWkNaVjYzcHMK/agcb+jI1tB8ANvHAn3HhHFYysTJDN43
        fX5ISkMHiQAsM5o3cQ5SUtgek26Q5m2nw+94FzpZJluwJmdOq+IVqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-20T05:21:43Z"
  mac: ENC[AES256_GCM,data:+C6GDxPT1UQ1J1tSwlwEa6ZRXbXVpqsjIu+EP9qutj8qfrvtPXt/rDgvNeKNLhfV4P/bt8btY8saVXGNmhOGmlFxSEA9nPJtoZ2sfgMH8a51xwt+Yq3CV+ZPZkEE8SKZuI/nNQgzv8YigeJpQh7JyE1Pf3nX6sLeRcSWtJWC03E=,iv:57UlzJ6ua9CK3z+OQHuBJACbdwdI4VU/ZCxP2UvGd28=,tag:Bl1erN7B36lAnGdz4FqxOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
