# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:EQ64RFrLWpiUtw==,iv:YZUkKbIj/7fN5Wno9rmk2JXBaeoq9bKdoq5DlrfPjZs=,tag:9DG9xhcRyDa8FYnpt8da9Q==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:/UthrysP7Vd0SS0cvx0R4iTWExe2s2tgAUy/JOGtRVJ1g1hCC7zKQg==,iv:9tmRKXIKyY0I98pa20TpaEcNyNL8YOiN3ZB8OM3NOpM=,tag:EiO867Qh2XHL/8g1F5ZI1A==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:gDEm/iGT6ATItQ0nip8G4+hdHgjpQ0FAhsazcdXqX8tKiUMK9cdLF3Ch6vA5mwhNjUBMGXFDsre0PF4uBn2lgolAbnKhdNdtTFqWqJnlwWCtWzq5HF/wpV1MzPmRN40pMNV6lqwuGg4IXyjRaPNNosY6Rqk+PS6x+na3kH7aE78=,iv:r4zyiRR4o1iRJt/n8N3IBdqhSWKJu+wcrfQkjnoov7g=,tag:dR1jsTLV0Rp5iZFb47tBBQ==,type:str]
  #ENC[AES256_GCM,data:DbgOydg2mu4sWlU=,iv:BLYg72w3xZXuImAyJgy3AmGgkeS/lqk22ZXCFqd8RVQ=,tag:jnGKSW2heuzySTGduIXLCg==,type:comment]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:o3UY2nM=,iv:c3NEsOpUTTb8ZYVssXgZ3XjF2tCVUiA8R1zyngQ7CNo=,tag:LdLl6Xhsk8Jg/HSWIjpONQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Vb6SJHxMP8MtXik636wiTtwSri9wf3Yu3Mtu0A==,iv:aZB+tC5+Mcp+MoawlWahaaX74cKdQw+B3eIoF96RJ+8=,tag:urINPlW6D2rPBCmx1PQsaQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEFCWE50ZjFnbEhGeksy
        WDMzeWN6WnFvTXFKTVpyVGJsV3NSSHlHcEhNCk9DRnhMOTJINWlVWksxdSswbTNW
        WnhUd01hVldhWmZiSEh5UUhZdjEyWG8KLS0tIDh5Qzl4UDVvN2pKc2ZEd0ZucXJx
        cFNQSUZGUFlwV0hDUlpTT2NFS0UxRW8KH9Fd2zPHpTZ9r3xRckrb0S30/gKZUZY2
        s7HA5kaqrF4VlzJWTaqJ1YOQd29+wpJ/XFu9IcIoSbnSCyJB4WvwJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T07:26:24Z"
  mac: ENC[AES256_GCM,data:D1s/Mi1ShahctzRvfvbAYCxKjh8iGDTlfm72xZJZheNTPO6kZYOiP9qOpJ2a9EfB9EgYzx9y3eVIXcREEKhnojz0XTSqjmGo2lOT2FqoiPa9jP80XYcGQ8+rAvMTOGZH+BKUqBPq4jEFdKLxA3fDMxi6eHojNDM0F1WHgYY9TjI=,iv:AlCTJza2koz9H9VKLL9K3jEc5HtcXg7sntv0tIJlW0s=,tag:TQeHFKo6UGmqqHdPyndAaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
