# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:WdTa1JcgC9EWKQ==,iv:o8edWchhbUtlyd1Q/zDC1dOACbnbs3OFtapHaQgQwZ4=,tag:dAuT650bT5/hnTETq6qLUg==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:DyZqWe40NimbJm4bYXB0WGasWeY4cVWvw9JlbevHJ9p9/9mXi+b1yQ==,iv:imfSRIDkB1veqWpz+RLfxl14aFGVztCwc9qzXsLxGmQ=,tag:5Z/2occrBrs6yBFQsXTmMg==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:OB/CEv0v4f1+xQLm3Y5Z/Mzqg52pK3Y5gzfYF5y1mpz6JomYJCpYDfljprKpWaVdFogLY3Vu9YJdhI6tsIMqAw80UH4+vOlptm0MWYZfIiopr8bYPsLReXymqP0Fm3XN4GxJloD8yee3NX4nFgUC/PTSxGmpSMUeV/PwQwE2svg=,iv:SqdmOyVHrsSDQKJPrsBWPNGiL26Y+b3uiXke8JrTe7Q=,tag:Xxk0Yvy05R346vs7PuU5Kw==,type:str]
  #ENC[AES256_GCM,data:eYJSK9k7f1WTTNo=,iv:DbbFr5Z4r0K04bNhx6Xgx6e81Ge92//gkbJfGkWS0tM=,tag:uDj7Pon6rlXiQzp8jr7/2Q==,type:comment]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:Ovj77uA=,iv:COdNk8toOS8kjf3gQdbLYH3acSPpzRobIe2ev0PdqGA=,tag:omtRIKXw/VGVU9n2mKWE7g==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:vtruWsC0+TxQT9YoqQb5wfelgMvK+wFF4kf7rw==,iv:VN09hiyXO3ogadJyfdZyvY2mVreGW0CWCIpdbMsPRn4=,tag:F1q4oyBf0A782CiUP58lhg==,type:str]
  #ENC[AES256_GCM,data:PDl//ZFblj7Oc53NKI9tG44rnf+97KjPe+S/Sjx9Nfn0f/8MSqRC+y7yYEpG9S8WIUg/oqJDQ5RsdvE2nAfgUmw5eNJYVg==,iv:VgrI/LZ9oHWRKI3ORzR8kukzmmt7KsMMVClXhD5bEcg=,tag:fhFMwL0nWJXZc4ocv4YRyQ==,type:comment]
  admin-user: ENC[AES256_GCM,data:h0y6X70=,iv:ADu2iex2TlAiUjNz3Y5YXVq3O3CoxoFQKYUp6BdkoLU=,tag:+wFSiXFA69ad+NuOET8C7g==,type:str]
  admin-password: ENC[AES256_GCM,data:ds+MAbNOTmxdrlyiVXHZK24//KAzIllFtgqwJA==,iv:TyiH2+yhL7nmRDSTzGvf//aprBTcxcHXgpAfTH9Rhn4=,tag:AAWqjtFhX0p4QzOY12tfOQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbDAzd0hmMHFDTjhyOTBw
        ckN1eXNHNndkc1ViTmgxbENMS3ZUb0pOR0M0CjN6elROWi9HTm1td3F2Tm4zUVdL
        dnlyNWV5a3hoeHdObFVUQ1QrTkEyOHMKLS0tIDJpQkxSS25lM3YrWTZVTnRCZ3NM
        c3pJeWMvQ21JblJUN0IyQ2VkMXBvcmsKT/tkgWy6nZSl5O0m02LW/5U7QUcgdKQf
        wZCZjX5QgzfeMh55cjPXvGmfG1nizd2uQjGQuVka2nRZRjJVO9XtLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T06:16:26Z"
  mac: ENC[AES256_GCM,data:EUnt7L4D367tKfexQLNHBMKV4MFBdpB+rRrxOrnNVSwhFEC8FNHHOUO2N/MOQaP5xFYMFVqDSTcJqqCvRaOZqfUFkHeImp9VsYFgnJpIg6WHr/yLXfugQEH3CCA+5zTnreZE8yeFZ1xkBfdjaE10r8Q/umANe0LMvIn6RBkXiZ0=,iv:RaUE8LZuDmhqfUgTJCU7WTWXFKMfH4SzNtxNrZi8T8o=,tag:58Fl+nTk2pEpjVsiSH8G+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
