# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:f+9LT+0p4XV9AssF1k39Tsvoqm74lsZ66ym/lVhXSUc=,iv:6ml0JB21PbaiIugyJgZapHhBCrf9xN9piB6/hsx+JVM=,tag:jhycdD8YHctIsSL4d1XYJQ==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK09jLzY4WVBMZnlRU2ZE
        R0x2eXR2clgrYm9vZ3RKK3VjbTJITnR0NEFBCkJzZHB3SWx3WEk5VXlRSXVOTCtX
        Tm9LWGlnUkV1UnRDSmJIT1ZXNVVTTmMKLS0tIGVKbEQ1a1pIRWZsL0phMUVDVzBJ
        ZDBvWjBkSFBERC9WUmtLZjB6bVBXMlkKLJxawAib1vcZyG5QQe/LZyTs31ctp9te
        YTj0CeQcuCUBC5IPSIKXq6aoVPA29RNzYCde/STlyiVpKOua6A7liA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T08:35:15Z"
  mac: ENC[AES256_GCM,data:oLtblcjdZAE+UWdlsMWwg7vOroTx08nwGF3Nbv41DnqXpFsMSggZ5DRNfUn+ncNT/lUkjV4WXiR84BO8f122lvLYHiBblqbauoFeYuN0XLvFqKs+KdkhLBzQ47OhMsDeQnCvfGz6mUOordCVYB4mgCXJxjDqbmNy+2XIfpfe7ew=,iv:AbO1WqGin+T4piYcHYDrYY5sL0JG6DmhtI76XC/L4w4=,tag:oNyRRsxo0wBOKQzjkv1m8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
