# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
stringData:
  IMMICH_DB_URI: ENC[AES256_GCM,data:RM/oyyoCH7DZePTjLIP+2pJ/uCRYOF6RrRcyKnr5Lz7OZNEn98yfZdFNDk7s0nwAj1IZfSULClsuLuX0hdWnKJWvTWr/N+BgVs4AsFQ1FYiNQyM2hBlVNf0o9N7DMd3hA6hB3Q0eh2YXlm3M9X54,iv:CK5jyxjiZrUd+IFFPkk2j0kBhHvs8xkpBASFoIKgfaA=,tag:iT/c4GphMRzGeI2CK4Iqdw==,type:str]
  #ENC[AES256_GCM,data:GV0Q5wG0,iv:0X46HgjB9ljVUNrWWDHSQYzwhOa6yFVqdbXc+Q+BIA8=,tag:/1JYvyKg0VG2Zc0cO73+3A==,type:comment]
  IMMICH_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:hOmsR4DMkrNkVDJmkvgp5MtaZD6fME1VWAGzIKp2uoDB/PIQ59rRQA==,iv:yknbOR3HNjgBMMWIweFZjsZ9jj83Pv9HgwUtjtAIgZQ=,tag:jb9oY39Y0zmox9U0PEjM1g==,type:str]
  IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hRPNIwD+zwJmycRcTDEccjMZYb3uLk4FVacZqSO0IFfK1msG7COB2DOUaLWezCXti25G3b+UiHPvVKEs3gFwpfcuAceUDrz5RBHCNAEiMBH7cLOuXqes4CW8u7a/Tt+MnclDY6jnJ2a78pOCYg0iLV4qx6k1b0qOyDB5ROanRtM=,iv:nXrxWc9TLf3iaIjADH0Of/nEIUkAxRjHtxtCOwQ1hw4=,tag:4+8fwI8BfsOGZ0tzKz5mBQ==,type:str]
  #ENC[AES256_GCM,data:btAYdpnf,iv:JdysaNSkwjaUJhPSEubWrJwV39+lmESHUodXV3mU0fo=,tag:htA0p2dQIsytqeb/I3mcfw==,type:comment]
  EMAIL_SERVER: ""
  EMAIL_USER: ""
  EMAIL_FROM: ENC[AES256_GCM,data:T/SNGor44yekERWI0D0FhKnY8PigSWE=,iv:aQhABgQ92nd2Ryef+UfOSqY0suuYKs4SVNB2iIvTmto=,tag:rQAqNbv9YgwmD0922/Ft9w==,type:str]
  EMAIL_PASS: ""
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcVNLbUdlbFM1NTNZRkF4
        QW12Ymhrb0VxYmJ6ZUNHS0hqVlcvcWs2NVRVCmZscDJGeFZ2YUZOdjVVelhpQ0o2
        R0U0dDJpTWltd3VQZ2hXenFtMGROUG8KLS0tIDJPaGkzYXZDL2lqUGhCU083a2ND
        Y1VTWG85dVNPWTFLbmIrWGIvcnBXUlUKrpx16u4AnNxvggBvg7IlPaoWEf8Y53oc
        OScgFPLKGPhptATymmHcWYmFLCg1h9Pcjc9GaNcfhMHHLv6J6t9HrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T04:02:32Z"
  mac: ENC[AES256_GCM,data:BxueQFXdJm1NdlFgL/xAD8HGEEKAmqPMkLQ/pmQZ3hRuyZJW1qtDjQl7ek2P6XHguCpLko+b20tWhvdvEXNRfsUBATnDoD4+iD9S49Pn9eenD090PXhuqV10zvrXibOiLA/dkzleJt1gof90F+O3M26XXPLuJ96CQQLPkSFvOtU=,iv:30rMXm0JxEjN4hknqKa0hD7DP4d3WwstSxV5fcQC2mA=,tag:BVZcU/ytTLldALPmySzc1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
