---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app syncthing-config
  namespace: &namespace self-hosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: longhorn
      namespace: storage
  interval: 1h
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/self-hosted/syncthing/config
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_CACHE_SNAPSHOTCLASS: longhorn-fast
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app syncthing
  namespace: &namespace self-hosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: syncthing-config
    - name: longhorn
      namespace: storage
  interval: 1h
  path: ./kubernetes/apps/self-hosted/syncthing/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_CACHE_SNAPSHOTCLASS: longhorn-fast
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_SCHEDULE: "0 0/4 * * *"
      VOLSYNC_HOURLY: "6"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false