# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:OErd8DuHI9ZPTqRxOfvTL/b1DYCTQlZ3ba3yE489qSs=,iv:6ccepfIWZgp0LQp4MDaHvI3FOeknhShzlEd1lkmzKqM=,tag:JZuQ8MAo5RKAkqVvwwxnfA==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYzNTR0dwU1hhcEs1TUI2
        Qk1VNzNpSno2RXoycGQvSUY0ZnVnMWxnMmpnCm51ZXFscmd1SzRJTmNtdkRud3Mz
        L08zM1RnYVNPN0U3L3RNeGMzRVRiS1UKLS0tIFk2ckV1SUFTSlY1Tkk3NkcxanZx
        bGR6SjlZVEx0aUxFZmE0S3F4ajl1amsK720YzIAmLTnywP/kzyJWaOG5T7HxJjHi
        TPsqq1J+8uU45aAQH/7td6kjCvtefD5EmZbxvMshrI8ARyTeTMoEMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T07:49:49Z"
  mac: ENC[AES256_GCM,data:RMfXAfTLxf3XXGozNlAI8SAhT2zC0i5vKvoTWAaGxVPPJZyhG9fxgqzgwIkRTTDo775jpZrQhoFNjarOku4sO6T8BeeMLPcyIA0KvzPzv5noYuY0PXTc/tSjq0eo3f0Sd6BhfZaTtU10cIKw3s8ZJ5E0GiB5GYDTUaOHgaCCdfw=,iv:47p43jDSFFkqbCR3out2yHPT3JpZhwbmQuejSRhmqLc=,tag:N0frEkxv18HXtN6/TRIQKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
