# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:OIKvQTjcrCRXcQ8Tfb+FVNFR6ux44S95KhCWaJQT7D0=,iv:1C6SZvxVlDb8pwYtn5puckTsSq75Zdccu8druHz0M1k=,tag:NTw8F6lgXx+JEZPzY43UdA==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUU8zWnh4cWJ5RVY1U09q
        bUF4Q1l1V2t0T3ZZTllnNExkS0x0RzVuUkdVCnRCU3k0STRTRTdVNC9HZlNGd2lq
        QytsRVAxMUpGQ3VLb0VQSUliYTVtQWMKLS0tIE1lSW9ORWRvYnFHYVZIamt6Z214
        Y3B4dmxobS9jdDVYaVh2bjdoZ3huS00KDvQHtBsCzAnaJTsrAq7ZZyj5LzlU3Bmy
        ZVZci8SbtygzgTBBYFinyXw6+5ctBwcNtngwueACj/9ujTGyRZtD+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-18T04:55:51Z"
  mac: ENC[AES256_GCM,data:W1I07xLzTkkX6AcQ55ddL93baPutS29w0dTXg5vGTkVqYbhQeGghcuU5TPnqmLCk4hFiuX0F8EN6T1i6sYk4Wa/qgKyYAE8bFaRkpYkTrlM/oBjN8diipb8ItghBmMB90DRMKqwAnisuKM827nQLnRzlvT83UUDHQiJEye4UHXE=,iv:iDzH3LVh6UwIzUWGAv1TmDf2sdL1Iqz9AZwQeXp3fK8=,tag:7xKsW89G0kS2nNibi7AJAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
