---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
spec:
  enabled: true
  trigger:
    schedule: "0 */12 * * *"
  repository:
    repository: volsync-maintenance-secret
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 4012
    runAsGroup: 4014
    fsGroup: 4014
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [4012, 4014]
