---
# yaml-language-server: $schema=$schema=https://kubernetes-schemas.pages.dev/barmancloud.cnpg.io/objectstore_v1.json
# technically we only need one of these per namespace...
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-${APP}
spec:
  retentionPolicy: 30d
  configuration:
    wal:
      compression: bzip2
      maxParallel: 8
      encryption: AES256
    data:
      compression: bzip2
      encryption: AES256
    destinationPath: s3://${BB_BUCKET}/
    endpointURL: ${BB_URL}
    s3Credentials:
      accessKeyId:
        name: &secret ${APP}-cnpg-secret
        key: BB_ACCESS_KEY_ID
      secretAccessKey:
        name: *secret
        key: BB_SECRET_ACCESS_KEY