---
# yaml-language-server: $schema=$schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: 'postgres-${APP}-daily-backup'
spec:
  immediate: true
  backupOwnerReference: self
  schedule: '@daily'
  cluster:
    name: 'postgres-${APP}'
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io