# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
stringData:
  ATUIN_DB_URI: ENC[AES256_GCM,data:fh4i7YHByPR9F1w70gYEEOZInx2NA1Ri6P1KQGMsLYpRuPeZc3t657RStOoIbzHeFSdTFmXazQFefu/rufLPNR1NrZbD+PSZ2ho81pAd8r48C5I9dLfXrC///dTVV9yrkiU8NGYVXhoG+AfK,iv:vvU+KH+S5y6iKpoJ1wS761R1Mr3s4oYOZKGTyjUl7Ng=,tag:dVk+OPdcXoPe4iQXfFiz2Q==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa1ZoaldmTnVBYUdYekM2
        ZklwTU5OcGRxdDhubUtTZG8wbmhpcjNlaEFzCnZkaDBnVHhzejJ4U2g3SmxDVlhi
        Q2M1ODFMU0pva0gzcTdaMnZkeElxWjAKLS0tIGFaemt1NTgzNjd6RzFoMDZLVkRD
        NXVvaDFVeGNkWmpJS3ZUdzZQeHJ2MlkKZUbDcD/n7fdMiMwtWg718lP6kBfe3JKb
        sMJ6mf+HBzaoA11iLoyGvll2KhPjL8pUv8Q4nbrB16wY5GrmV1zgZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T21:28:48Z"
  mac: ENC[AES256_GCM,data:hyc0/qNOKyRvLJ7kNokxe5SIDiiWBRt5RhxB31Mlk+UAZe5y2C0NytnyB39LEe0AKEGab98y5tzaxtUwVyqLQXKGbU3Qq/+EVgJNJA38wKGsBFclDJq/rQAphAb0xgC3Z4qYfFojIDVlsYR5Kkr3mLQfmDxAT/jOOIGm/2aMQ/k=,iv:rUb0wCYfSrXsc/3Bn1cTGNn0W2Bj0hyFT8mhOuzF6X0=,tag:yBbScWcghKGqxl+CowXYFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
