apiVersion: v1
kind: Secret
metadata:
  name: ubuntu-dev-credentials
type: Opaque
stringData:
  nospamas: ENC[AES256_GCM,data:/Mp35u58iMv0i5e3SMvCClI8TD9TirbDyFP+Mt/C,iv:cRw/CR1YPAZjfyhuMnfpUIX2GGiUbqZKijA8dDt0pok=,tag:XcefmqAQeXeP30tteKoBEw==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRWJ0dzVnZ1ZacVdydkJE
        ZWxWRTU5VmVVVTkraklEZFhTMnRYb0FsRzFNCmZ3dTVyZENSS09HVjhDTms1QURP
        NVZRWWg1WGpFajE3TDQvK0h5b3hqRnMKLS0tIC9nVUc1cjRpRzBOQnlrVGNwYmtj
        VFdUVUIrbTRpOHMvZHl0ZDlpMW5ZNWsKD2M5PHjahGg5gFksOoRGlMCT6bb29Rr7
        BIeI+svN9aT+t8j7oaZwjo+UiOchbhebC1we+/0iEfT85LjbZKO2FA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-19T05:28:46Z"
  mac: ENC[AES256_GCM,data:3+4pRr0pn0YuwWQi/ib2q8BaoULaRFXkCKOdcjk62jkuP1eLgDJkENVt6Z/mNkfWaVU2cQFkyMMrfSzOVkGFTkVF08UvBMA41Xu2QIq+y5LBYHT5ZK/Bz5yRZqW4vrtgoZs09iHyIWgG6KUvPzEqHo3hCzEXf2nzVUzePPue/8w=,iv:sEcbsNbwqFkyCWOklkxhuFmCtfh0PaFFbQJZll+cHi0=,tag:2gKg5lxCBtW/+yeI+YNTYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
