apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  annotations:
  name: renovate-github
  namespace: renovate-operator
spec:
  schedule: 0 * * * *
  discoveryFilter: nospamas/home-ops
  extraEnv:
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    # - name: RENOVATE_LOG_LEVEL
    #   value: debug
  image: ghcr.io/renovatebot/renovate:42.64.0@sha256:5baf89c20738985b2ba2d9a2e1b66265cb2cb514e095d87d49f9c331e377e983
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: renovate-secret