apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  annotations:
  name: renovate-github
  namespace: renovate-operator
spec:
  schedule: 0 * * * *
  discoveryFilter: nospamas/home-ops
  extraEnv:
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
    # - name: RENOVATE_LOG_LEVEL
    #   value: debug
  image: ghcr.io/renovatebot/renovate:42.66.8@sha256:12bf830288fe3935bcfa41ed7577c59bee6a03f1b0b7d91f86a70484bc2d949c
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  secretRef: renovate-secret