kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: renovate-secret
stringData:
  GITHUB_COM_USER: ENC[AES256_GCM,data:iVv4ZldRlfU=,iv:8UiFDbSwYnxvs/XFTXBqJi2ulLU4Nqeu7DXMPMHv9ds=,tag:NQahh3sqqPvOuSAAXA1Ihw==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:ah3CjexnFdwRNJoU7RfLxUicR6eWiAwoiHXNP8uk5P+Pd0fnRmByL69vfEWzW8VoHctF0HNLpzkIr4uhmIsKzL3kTsP0mlSxaReQcS0odvc79iwiWgHZiMo8kOQB,iv:ypcs8YNZGd1KvUEvgpip+Y836iNrhZL93dBUSWYqnGg=,tag:bm+XIGYSbYzbDIl9QiE2wg==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:g42JG8gTPgtdGcDFia2oGByuugCdtUlS8dkmilJRVPfST/pAe1ij+Z44zG7Qxd9ekRIDGIlrnnoOlKZR7VcdoHuDxYH3u56DopK9yMGCkONjdtCPpxk8mhzHEp7R,iv:zX6kw9fKlaiML8oNU8GtskRHvfRdvzBJ0t3XYRbt1Fk=,tag:sfxFXaviFo3zW0Jl8ZzVrg==,type:str]
sops:
  age:
    - recipient: age1sq0wjrxgd2p0kl55cl22306l3lyzt5n0hdmqny6tr9qfkwyxu3aszelc7a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMk9ibVV0UTFaR3puMmp5
        eklvbGROaTZiek50aFpqNFAyK1ZEVHZFd0NZCjl5cGhqTnBQYUxQVGs5L0hNOWpU
        RlUwQWtQRSs2cmEvV2x2M0dUVC9UV0kKLS0tIGVwWGlKalZocnd5aEpadEV4Wmw3
        cXdTTHgyWk5GYnFTRHpRcGpzNDJCYlUK/XAJ2WcDT9DEKcz5fhTEWZR5MKvfNL2c
        JMoUx4Zjgu1ZlAkMF1MXhbANpjt/OiKjy433sXHHCgdLRnOr0l8aew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T05:02:48Z"
  mac: ENC[AES256_GCM,data:0bk/m/bBLu3pxdXWjWpULghX9hj2cTq436IzWyR2EhfCMOO2F5L8OBAHcoh7/lB4X1eTNdKjUIpKD5ENQ8DIFhqEV4j8Uu7xulaek1vwshFq0UmRGeJBXSnwLnFxvNvAwbcfTkV7eFYHawSGOJ7S/Dit3stBC4/mSbloUNio38I=,iv:T8Z7OQPOl/Ygt0eZ4xq60SRpIXr/ruHiCfND1JkDJFQ=,tag:JCQR71l6abuBWlnUiieRCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
